version: '2.3'
services:
  moveit:
    container_name: moveit
    image: moveit:melodic
    environment:
      WAIT_FOR_ROSCORE: 1
      ROS_IP: 127.0.0.1
      ROS_MASTER_URI: http://127.0.0.1:11311
      ROS_HOSTNAME: 127.0.0.1
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: '1'
    stdin_open: true
    restart: 'unless-stopped'
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /home/sai/catkin_ws/src/sp-192149_tier3:/root/catkin_ws/src/sp-192149_tier3
      - /home/sai/catkin_ws/src/sp-192149_tier4:/root/catkin_ws/src/sp-192149_tier4
    command: tail -f /dev/null
