version: '2.3'
services:
  tiago-base:
    image: fbe-dockerreg.rwu.de/prj-iki-robotics/robots/kurt-simulation:master-melodic
    environment:
        ROS_IP: 127.0.0.1
        ROS_HOSTNAME: 127.0.0.1
        ROS_MASTER_URI: http://127.0.0.1:11311
        DISPLAY: $DISPLAY
        QT_X11_NO_MITSHM: '1'
        NVIDIA_VISIBLE_DEVICES: all
        NVIDIA_DRIVER_CAPABILITIES: compute,video,utility,graphics
    network_mode: host
    privileged: true
    stdin_open: true
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - $HOME/.Xauthority:/root/.Xauthority
        - /home/sai/catkin_ws/src/sp-192149_tier4:/root/catkin_ws/src/sp-192149_tier4
        - /home/sai/catkin_ws/src/sp-192149_tier3:/root/catkin_ws/src/sp-192149_tier3
          #command: tail -f /dev/null
    command: roslaunch kurt_bringup_sim kurt_sim_nav.launch world:=/root/catkin_ws/src/sp-192149_tier4/world/test5.sdf  map:=/root/catkin_ws/src/prj-iki-robotics/knowledgebase/ros-iki-object-models/iki_object_models/models/robo_lab/map gzpose:="-x -3.0 -y 5.0 -z 0.0 -R 0.0 -P 0.0 -Y 0.0"


